//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckboxStation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckboxStation.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All instruments have been checked out. Do you want to finish the operation?.
        /// </summary>
        internal static string All_checked_out {
            get {
                return ResourceManager.GetString("All checked out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to finish the check-in session?.
        /// </summary>
        internal static string Are_you_sure_that_you_want_to_finish_the_check_in_session_ {
            get {
                return ResourceManager.GetString("Are you sure that you want to finish the check-in session?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string BrandColumnHeaderText {
            get {
                return ResourceManager.GetString("BrandColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in.
        /// </summary>
        internal static string Check_in {
            get {
                return ResourceManager.GetString("Check in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the instruments you scanned are already checked in in another session that has not been completed..
        /// </summary>
        internal static string CheckInAssetAlreadyCheckedInInAnotherSession {
            get {
                return ResourceManager.GetString("CheckInAssetAlreadyCheckedInInAnotherSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in failed.
        /// </summary>
        internal static string CheckInFailed {
            get {
                return ResourceManager.GetString("CheckInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out failed.
        /// </summary>
        internal static string CheckOutFailed {
            get {
                return ResourceManager.GetString("CheckOutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operation chosen. An operation must be chosen!
        ///If the desired operation is not visible, create or start an operation in the &apos;Operations&apos; tab..
        /// </summary>
        internal static string Choose_operation {
            get {
                return ResourceManager.GetString("Choose operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        internal static string Continue_ {
            get {
                return ResourceManager.GetString("Continue?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active operations. Create or start an operation in the &apos;Operations&apos; tab. .
        /// </summary>
        internal static string Create_or_start_operation {
            get {
                return ResourceManager.GetString("Create or start operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionCoulmnHeaderText {
            get {
                return ResourceManager.GetString("DescriptionCoulmnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description ID.
        /// </summary>
        internal static string DescriptionIdCoulmnHeaderText {
            get {
                return ResourceManager.GetString("DescriptionIdCoulmnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish check in.
        /// </summary>
        internal static string Finish_check_in {
            get {
                return ResourceManager.GetString("Finish check in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish operation.
        /// </summary>
        internal static string Finish_operation {
            get {
                return ResourceManager.GetString("Finish operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish check in failed.
        /// </summary>
        internal static string FinishCheckInFailed {
            get {
                return ResourceManager.GetString("FinishCheckInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruments successfully checked out!.
        /// </summary>
        internal static string Instrument_check_out {
            get {
                return ResourceManager.GetString("Instrument check out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned mix of instruments that are checked in and checked out. Can only check in or check out at one time. 
        ///Remove instruments and scan again. .
        /// </summary>
        internal static string Instrument_mix {
            get {
                return ResourceManager.GetString("Instrument mix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruments successfully checked in!.
        /// </summary>
        internal static string Instruments_checked_in {
            get {
                return ResourceManager.GetString("Instruments checked in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruments successfully sent to service!.
        /// </summary>
        internal static string Instruments_sent_to_service {
            get {
                return ResourceManager.GetString("Instruments sent to service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbox Station.
        /// </summary>
        internal static string MainForm_StartupShowSplash_Checkbox_Station {
            get {
                return ResourceManager.GetString("MainForm_StartupShowSplash_Checkbox_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to SQL server: .
        /// </summary>
        internal static string MainForm_StartupShowSplash_Connecting_to_SQL_server__ {
            get {
                return ResourceManager.GetString("MainForm_StartupShowSplash_Connecting_to_SQL_server__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching for RFID reader ....
        /// </summary>
        internal static string MainForm_StartupShowSplash_Searching_for_RFID_reader____ {
            get {
                return ResourceManager.GetString("MainForm_StartupShowSplash_Searching_for_RFID_reader____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing instruments.
        /// </summary>
        internal static string Missing_instruments {
            get {
                return ResourceManager.GetString("Missing instruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mix of check-in/check-out.
        /// </summary>
        internal static string Mix_of_check_in_check_out {
            get {
                return ResourceManager.GetString("Mix of check-in/check-out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one tray scanned. \nPacking list NOT validated. \nChecking in: {Instruments.Count} instruments..
        /// </summary>
        internal static string More_than_one_tray_scanned___nPacking_list_NOT_validated___nChecking_in___Instruments_Count__instruments_ {
            get {
                return ResourceManager.GetString("More than one tray scanned. \\nPacking list NOT validated. \\nChecking in: {Instrum" +
                        "ents.Count} instruments.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one tray scanned!.
        /// </summary>
        internal static string More_trays_scanned {
            get {
                return ResourceManager.GetString("More trays scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active operation.
        /// </summary>
        internal static string No_active_operation {
            get {
                return ResourceManager.GetString("No active operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No operation chosen..
        /// </summary>
        internal static string No_operation_chosen_ {
            get {
                return ResourceManager.GetString("No operation chosen.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tray!.
        /// </summary>
        internal static string No_tray_ {
            get {
                return ResourceManager.GetString("No tray!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all instruments have been checked out! You can still finish the operation. 
        ///The instruments missing can be seen in Admin Station. Do you want to finish the operation with missing instruments?.
        /// </summary>
        internal static string Not_all_checked_out {
            get {
                return ResourceManager.GetString("Not all checked out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation finished!.
        /// </summary>
        internal static string Operation_finished_ {
            get {
                return ResourceManager.GetString("Operation finished!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing list was nok OK. This can because instruments are missing. Do you want to scan again?.
        /// </summary>
        internal static string Packing_list_error {
            get {
                return ResourceManager.GetString("Packing list error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string QuantityColumnHeaderText {
            get {
                return ResourceManager.GetString("QuantityColumnHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The report file has been successfully generated (session {0}, in {0} folder).
        ///If it has access, it will be also shared by email..
        /// </summary>
        internal static string ReportConfirmationDialogMessage {
            get {
                return ResourceManager.GetString("ReportConfirmationDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Generated.
        /// </summary>
        internal static string ReportConfirmationDialogTitle {
            get {
                return ResourceManager.GetString("ReportConfirmationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        internal static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
    }
}
