//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caretag_Class.My.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Main.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while performing database operations related to servicing the instrument.
        /// </summary>
        internal static string An_error_occurred_while_performing_database_operations_related_to_servicing_the_instrument {
            get {
                return ResourceManager.GetString("An error occurred while performing database operations related to servicing the i" +
                        "nstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string DialogButtonAll {
            get {
                return ResourceManager.GetString("DialogButtonAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DialogButtonCancel {
            get {
                return ResourceManager.GetString("DialogButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DialogButtonNo {
            get {
                return ResourceManager.GetString("DialogButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string DialogButtonOk {
            get {
                return ResourceManager.GetString("DialogButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string DialogButtonYes {
            get {
                return ResourceManager.GetString("DialogButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File To Import does NOT Exits Or EMPTY !!!.
        /// </summary>
        internal static string File_To_Import_does_NOT_Exits_Or_EMPTY____ {
            get {
                return ResourceManager.GetString("File To Import does NOT Exits Or EMPTY !!!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image File is NOT Found ...  .
        /// </summary>
        internal static string Image_File_is_NOT_Found____ {
            get {
                return ResourceManager.GetString("Image File is NOT Found ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue in Saving Image to Database  .
        /// </summary>
        internal static string Issue_in_Saving_Image_to_Database {
            get {
                return ResourceManager.GetString("Issue in Saving Image to Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue in Streaming Image to Database ....
        /// </summary>
        internal static string Issue_in_Streaming_Image_to_Database____ {
            get {
                return ResourceManager.GetString("Issue in Streaming Image to Database ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ETC Directory Exist ! - Please Report.
        /// </summary>
        internal static string No_ETC_Directory_Exist_____Please_Report {
            get {
                return ResourceManager.GetString("No ETC Directory Exist ! - Please Report", resourceCulture);
            }
        }
    }
}
