//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFIDAbstractionLayer.Simulator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RFIDAbstractionLayer.Simulator.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        public static string btnDefaults {
            get {
                return ResourceManager.GetString("btnDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string btnOK {
            get {
                return ResourceManager.GetString("btnOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to DB API.
        /// </summary>
        public static string CantConnectDBApiCaption {
            get {
                return ResourceManager.GetString("CantConnectDBApiCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to Database API. 
        ///
        ///Would you like to change login credentials?
        ///
        ///(Choosing &quot;no&quot; will load Hardcoded values).
        /// </summary>
        public static string CantConnectDBApiMsg {
            get {
                return ResourceManager.GetString("CantConnectDBApiMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuring Services ....
        /// </summary>
        public static string ConfiguringServices {
            get {
                return ResourceManager.GetString("ConfiguringServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to DB Api....
        /// </summary>
        public static string ConnectingToAPI {
            get {
                return ResourceManager.GetString("ConnectingToAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPC.
        /// </summary>
        public static string EPC {
            get {
                return ResourceManager.GetString("EPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in simulation.
        /// </summary>
        public static string ErrorInSimulation {
            get {
                return ResourceManager.GetString("ErrorInSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate ID.
        /// </summary>
        public static string GenerateID {
            get {
                return ResourceManager.GetString("GenerateID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Url.
        /// </summary>
        public static string lblApiUrl {
            get {
                return ResourceManager.GetString("lblApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string lblUserName {
            get {
                return ResourceManager.GetString("lblUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to load default values?.
        /// </summary>
        public static string LoadDefaultsMsg {
            get {
                return ResourceManager.GetString("LoadDefaultsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Default Values.
        /// </summary>
        public static string LoadDefaultsTitle {
            get {
                return ResourceManager.GetString("LoadDefaultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Settings ....
        /// </summary>
        public static string LoadingSettings {
            get {
                return ResourceManager.GetString("LoadingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Virtual Tag.
        /// </summary>
        public static string NewVirtualTag {
            get {
                return ResourceManager.GetString("NewVirtualTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power changed to {0}.
        /// </summary>
        public static string PowerChange {
            get {
                return ResourceManager.GetString("PowerChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string qdError {
            get {
                return ResourceManager.GetString("qdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string qdInformation {
            get {
                return ResourceManager.GetString("qdInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string qdNotAvail {
            get {
                return ResourceManager.GetString("qdNotAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t send an item with a Null EPC value.
        /// </summary>
        public static string qdNullEpcMsg {
            get {
                return ResourceManager.GetString("qdNullEpcMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string qdQuestion {
            get {
                return ResourceManager.GetString("qdQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Tag requires a connection to the DatabaseAPI. Please restart the program..
        /// </summary>
        public static string qdVirtualTagDBNeeded {
            get {
                return ResourceManager.GetString("qdVirtualTagDBNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string qdWarning {
            get {
                return ResourceManager.GetString("qdWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Quick Send .
        /// </summary>
        public static string quickBtn {
            get {
                return ResourceManager.GetString("quickBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Send EPC.
        /// </summary>
        public static string QuickSendEPCLbl {
            get {
                return ResourceManager.GetString("QuickSendEPCLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Search .
        /// </summary>
        public static string searchBtn {
            get {
                return ResourceManager.GetString("searchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string searchLbl {
            get {
                return ResourceManager.GetString("searchLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session History.
        /// </summary>
        public static string SessionSendHistoryLbl {
            get {
                return ResourceManager.GetString("SessionSendHistoryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag ID.
        /// </summary>
        public static string TagID {
            get {
                return ResourceManager.GetString("TagID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Simulator.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this tag already exists in the Database, it will break the Database.
        /// </summary>
        public static string VirtualTagWarning {
            get {
                return ResourceManager.GetString("VirtualTagWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING!!!.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
