//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnicalStation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechnicalStation.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &quot;Link Asset&quot; to change the type, or &quot;Restart&quot; to scan a new RFID tag..
        /// </summary>
        internal static string ActiveAssetOptions {
            get {
                return ResourceManager.GetString("ActiveAssetOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to connect to the database.
        /// </summary>
        internal static string An_error_occurred_when_trying_to_connect_to_the_database {
            get {
                return ResourceManager.GetString("An error occurred when trying to connect to the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the selected index.
        /// </summary>
        internal static string An_error_occurred_while_changing_the_selected_index {
            get {
                return ResourceManager.GetString("An error occurred while changing the selected index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the text.
        /// </summary>
        internal static string An_error_occurred_while_changing_the_text {
            get {
                return ResourceManager.GetString("An error occurred while changing the text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking if the item is in the database.
        /// </summary>
        internal static string An_error_occurred_while_checking_if_the_item_is_in_the_database {
            get {
                return ResourceManager.GetString("An error occurred while checking if the item is in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking if the Tag is Caretag.
        /// </summary>
        internal static string An_error_occurred_while_checking_if_the_Tag_is_Caretag {
            get {
                return ResourceManager.GetString("An error occurred while checking if the Tag is Caretag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking the reader.
        /// </summary>
        internal static string An_error_occurred_while_checking_the_reader {
            get {
                return ResourceManager.GetString("An error occurred while checking the reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while clicking the group description.
        /// </summary>
        internal static string An_error_occurred_while_clicking_the_group_description {
            get {
                return ResourceManager.GetString("An error occurred while clicking the group description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while clicking the Tag update button.
        /// </summary>
        internal static string An_error_occurred_while_clicking_the_Tag_update_button {
            get {
                return ResourceManager.GetString("An error occurred while clicking the Tag update button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the application.
        /// </summary>
        internal static string An_error_occurred_while_loading_the_application {
            get {
                return ResourceManager.GetString("An error occurred while loading the application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while making groups.
        /// </summary>
        internal static string An_error_occurred_while_making_groups {
            get {
                return ResourceManager.GetString("An error occurred while making groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while manipulating the text.
        /// </summary>
        internal static string An_error_occurred_while_manipulating_the_text {
            get {
                return ResourceManager.GetString("An error occurred while manipulating the text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while moving the mouse over the picturebox.
        /// </summary>
        internal static string An_error_occurred_while_moving_the_mouse_over_the_picturebox {
            get {
                return ResourceManager.GetString("An error occurred while moving the mouse over the picturebox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while pressing the video camera.
        /// </summary>
        internal static string An_error_occurred_while_pressing_the_video_camera {
            get {
                return ResourceManager.GetString("An error occurred while pressing the video camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while pressing the world picture.
        /// </summary>
        internal static string An_error_occurred_while_pressing_the_world_picture {
            get {
                return ResourceManager.GetString("An error occurred while pressing the world picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to add a label.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_add_a_label {
            get {
                return ResourceManager.GetString("An error occurred while trying to add a label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to add one EPC.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_add_one_EPC {
            get {
                return ResourceManager.GetString("An error occurred while trying to add one EPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to change the index.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_change_the_index {
            get {
                return ResourceManager.GetString("An error occurred while trying to change the index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to check if the TAG exists in the database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_check_if_the_TAG_exists_in_the_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to check if the TAG exists in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to check if the Tag is in the database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_check_if_the_Tag_is_in_the_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to check if the Tag is in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to check the TAG info.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_check_the_TAG_info {
            get {
                return ResourceManager.GetString("An error occurred while trying to check the TAG info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to check the Tag relation.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_check_the_Tag_relation {
            get {
                return ResourceManager.GetString("An error occurred while trying to check the Tag relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to clean up the interface.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_clean_up_the_interface {
            get {
                return ResourceManager.GetString("An error occurred while trying to clean up the interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to click the Camera.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_click_the_Camera {
            get {
                return ResourceManager.GetString("An error occurred while trying to click the Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to convert from Hex to Byte.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_convert_from_Hex_to_Byte {
            get {
                return ResourceManager.GetString("An error occurred while trying to convert from Hex to Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to convert Hex to Byte.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_convert_Hex_to_Byte {
            get {
                return ResourceManager.GetString("An error occurred while trying to convert Hex to Byte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to create the first REC.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_create_the_first_REC {
            get {
                return ResourceManager.GetString("An error occurred while trying to create the first REC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to delete the Tag from the database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_delete_the_Tag_from_the_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to delete the Tag from the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to display the pivotgrid text.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_display_the_pivotgrid_text {
            get {
                return ResourceManager.GetString("An error occurred while trying to display the pivotgrid text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to do maintenance for instrument RFID.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_do_maintenance_for_instrument_RFID {
            get {
                return ResourceManager.GetString("An error occurred while trying to do maintenance for instrument RFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to exit.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_exit {
            get {
                return ResourceManager.GetString("An error occurred while trying to exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to exit the form.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_exit_the_form {
            get {
                return ResourceManager.GetString("An error occurred while trying to exit the form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to exit the page.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_exit_the_page {
            get {
                return ResourceManager.GetString("An error occurred while trying to exit the page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to export the Excel.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_export_the_Excel {
            get {
                return ResourceManager.GetString("An error occurred while trying to export the Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to fill the description.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_fill_the_description {
            get {
                return ResourceManager.GetString("An error occurred while trying to fill the description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to fill the field.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_fill_the_field {
            get {
                return ResourceManager.GetString("An error occurred while trying to fill the field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to fill the tray combobox.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_fill_the_tray_combobox {
            get {
                return ResourceManager.GetString("An error occurred while trying to fill the tray combobox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to filter by ID.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_filter_by_ID {
            get {
                return ResourceManager.GetString("An error occurred while trying to filter by ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to filter by name.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_filter_by_name {
            get {
                return ResourceManager.GetString("An error occurred while trying to filter by name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to get a new EPC.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_get_a_new_EPC {
            get {
                return ResourceManager.GetString("An error occurred while trying to get a new EPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to get the ID back..
        /// </summary>
        internal static string An_error_occurred_while_trying_to_get_the_ID_back_ {
            get {
                return ResourceManager.GetString("An error occurred while trying to get the ID back.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to hide the hide the picturebox.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_hide_the_hide_the_picturebox {
            get {
                return ResourceManager.GetString("An error occurred while trying to hide the hide the picturebox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to initialize the Active Directory Login page.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_initialize_the_Active_Directory_Login_page {
            get {
                return ResourceManager.GetString("An error occurred while trying to initialize the Active Directory Login page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to insert a Tag in the database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_insert_a_Tag_in_the_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to insert a Tag in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to insert the item in the database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_insert_the_item_in_the_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to insert the item in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to insert the Tag in the database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_insert_the_Tag_in_the_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to insert the Tag in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to load the cart pivotgrid.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_load_the_cart_pivotgrid {
            get {
                return ResourceManager.GetString("An error occurred while trying to load the cart pivotgrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to load the company department.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_load_the_company_department {
            get {
                return ResourceManager.GetString("An error occurred while trying to load the company department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to load the container pivotgrid.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_load_the_container_pivotgrid {
            get {
                return ResourceManager.GetString("An error occurred while trying to load the container pivotgrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to load the form.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_load_the_form {
            get {
                return ResourceManager.GetString("An error occurred while trying to load the form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to load the page.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_load_the_page {
            get {
                return ResourceManager.GetString("An error occurred while trying to load the page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to load the pivotgrid.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_load_the_pivotgrid {
            get {
                return ResourceManager.GetString("An error occurred while trying to load the pivotgrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to load the tray pivotgrid.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_load_the_tray_pivotgrid {
            get {
                return ResourceManager.GetString("An error occurred while trying to load the tray pivotgrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to Log a message in the database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_Log_a_message_in_the_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to Log a message in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to Log a message to the database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_Log_a_message_to_the_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to Log a message to the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to Log to the database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_Log_to_the_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to Log to the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to LogIn.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_LogIn {
            get {
                return ResourceManager.GetString("An error occurred while trying to LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to make a group identifier.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_make_a_group_identifier {
            get {
                return ResourceManager.GetString("An error occurred while trying to make a group identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to make a new EPC.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_make_a_new_EPC {
            get {
                return ResourceManager.GetString("An error occurred while trying to make a new EPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to open an image.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_open_an_image {
            get {
                return ResourceManager.GetString("An error occurred while trying to open an image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to open the Department window.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_open_the_Department_window {
            get {
                return ResourceManager.GetString("An error occurred while trying to open the Department window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to read the next instrument.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_read_the_next_instrument {
            get {
                return ResourceManager.GetString("An error occurred while trying to read the next instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to read the SEQ.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_read_the_SEQ {
            get {
                return ResourceManager.GetString("An error occurred while trying to read the SEQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to save a Log to the database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_save_a_Log_to_the_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to save a Log to the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to save the image.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_save_the_image {
            get {
                return ResourceManager.GetString("An error occurred while trying to save the image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to substract one EPC.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_substract_one_EPC {
            get {
                return ResourceManager.GetString("An error occurred while trying to substract one EPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to Tag an EPC.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_Tag_an_EPC {
            get {
                return ResourceManager.GetString("An error occurred while trying to Tag an EPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to update the database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_update_the_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to update the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to update the serial number.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_update_the_serial_number {
            get {
                return ResourceManager.GetString("An error occurred while trying to update the serial number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to update the Tag from the database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_update_the_Tag_from_the_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to update the Tag from the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to update the Tag in the database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_update_the_Tag_in_the_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to update the Tag in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to update the Tag info.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_update_the_Tag_info {
            get {
                return ResourceManager.GetString("An error occurred while trying to update the Tag info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to verify if the TAG is active in another database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_verify_if_the_TAG_is_active_in_another_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to verify if the TAG is active in another database" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying update the Tag info.
        /// </summary>
        internal static string An_error_occurred_while_trying_update_the_Tag_info {
            get {
                return ResourceManager.GetString("An error occurred while trying update the Tag info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error related to the TAG occurred while trying to make a new EPC.
        /// </summary>
        internal static string An_error_related_to_the_TAG_occurred_while_trying_to_make_a_new_EPC {
            get {
                return ResourceManager.GetString("An error related to the TAG occurred while trying to make a new EPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed! Please check your internet connection..
        /// </summary>
        internal static string ApiLoginFailed {
            get {
                return ResourceManager.GetString("ApiLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppInstanceId is missing. Please ensure that the configuration contains an AppData section containing the AppInstanceId and restart the application..
        /// </summary>
        internal static string AppinstanceIdMissing {
            get {
                return ResourceManager.GetString("AppinstanceIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article SKU.
        /// </summary>
        internal static string ArticleSKU {
            get {
                return ResourceManager.GetString("ArticleSKU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset is already a container..
        /// </summary>
        internal static string AssetIsContainer {
            get {
                return ResourceManager.GetString("AssetIsContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset is already a tray..
        /// </summary>
        internal static string AssetIsTray {
            get {
                return ResourceManager.GetString("AssetIsTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to program tag..
        /// </summary>
        internal static string AttemptingToProgramTag {
            get {
                return ResourceManager.GetString("AttemptingToProgramTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be aware NO Reader can be Found ! .....
        /// </summary>
        internal static string Be_aware_NO_Reader_can_be_Found_______ {
            get {
                return ResourceManager.GetString("Be aware NO Reader can be Found ! ....", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change asset type to container. If the asset was programmed by mistake, it must be reset..
        /// </summary>
        internal static string CannotChangeAssetTypeToContainer {
            get {
                return ResourceManager.GetString("CannotChangeAssetTypeToContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change asset type to instrument. If the asset was programmed by mistake, it must be reset..
        /// </summary>
        internal static string CannotChangeAssetTypeToInstrument {
            get {
                return ResourceManager.GetString("CannotChangeAssetTypeToInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change asset type to sterilization cart. If the asset was programmed by mistake, it must be reset..
        /// </summary>
        internal static string CannotChangeAssetTypeToSterilizationCart {
            get {
                return ResourceManager.GetString("CannotChangeAssetTypeToSterilizationCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change asset type to tray. If the asset was programmed by mistake, it must be reset..
        /// </summary>
        internal static string CannotChangeAssetTypeToTray {
            get {
                return ResourceManager.GetString("CannotChangeAssetTypeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change asset type to surgical trolley. If the asset was programmed by mistake, it must be reset..
        /// </summary>
        internal static string CannotChangeAssetTypeToTrolley {
            get {
                return ResourceManager.GetString("CannotChangeAssetTypeToTrolley", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Click &apos;next&apos; to change instrument type or &apos;restart&apos; to scan a different asset..
        /// </summary>
        internal static string ChangeInstrumentType {
            get {
                return ResourceManager.GetString("ChangeInstrumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Version Or License  - An Issue !.
        /// </summary>
        internal static string Check_Version_Or_License____An_Issue__ {
            get {
                return ResourceManager.GetString("Check Version Or License  - An Issue !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Dot Net Version ....
        /// </summary>
        internal static string Checking_Dot_Net_Version____ {
            get {
                return ResourceManager.GetString("Checking Dot Net Version ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for Update ! .
        /// </summary>
        internal static string Checking_for_Update__ {
            get {
                return ResourceManager.GetString("Checking for Update !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Reader_ID ....
        /// </summary>
        internal static string Checking_Reader_ID____ {
            get {
                return ResourceManager.GetString("Checking Reader_ID ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Version &amp; License ....
        /// </summary>
        internal static string Checking_Version___License____ {
            get {
                return ResourceManager.GetString("Checking Version & License ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected....
        /// </summary>
        internal static string Connected___ {
            get {
                return ResourceManager.GetString("Connected...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to SQL_SERVER:.
        /// </summary>
        internal static string Connecting_to_SQL_SERVER_ {
            get {
                return ResourceManager.GetString("Connecting to SQL_SERVER:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to SQL_SERVER ... .
        /// </summary>
        internal static string Connecting_to_SQL_SERVER____ {
            get {
                return ResourceManager.GetString("Connecting to SQL_SERVER ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to database server.
        /// </summary>
        internal static string ConnectingDB {
            get {
                return ResourceManager.GetString("ConnectingDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact IT department Or Caretag !.
        /// </summary>
        internal static string Contact_IT_department_Or_Caretag__ {
            get {
                return ResourceManager.GetString("Contact IT department Or Caretag !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container saved!.
        /// </summary>
        internal static string ContainerSaved {
            get {
                return ResourceManager.GetString("ContainerSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Issue and Program is Shutting Down.
        /// </summary>
        internal static string Correct_Issue_and_Program_is_Shutting_Down {
            get {
                return ResourceManager.GetString("Correct Issue and Program is Shutting Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not program tag after 10 tries. Tag may not be mounted correctly. Reposition tag and try again..
        /// </summary>
        internal static string CouldNotProgramTag {
            get {
                return ResourceManager.GetString("CouldNotProgramTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days To Now.
        /// </summary>
        internal static string Day_To_Now {
            get {
                return ResourceManager.GetString("Day_To_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Configuration Used - Reader ID:.
        /// </summary>
        internal static string Default_Configuration_Used___Reader_ID_ {
            get {
                return ResourceManager.GetString("Default Configuration Used - Reader ID:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot Net Version ... is NOT Okay.
        /// </summary>
        internal static string Dot_Net_Version_____is_NOT_Okay {
            get {
                return ResourceManager.GetString("Dot Net Version ... is NOT Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot Net Version ... Is Okay.
        /// </summary>
        internal static string Dot_Net_Version_____Is_Okay {
            get {
                return ResourceManager.GetString("Dot Net Version ... Is Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 4 characters to search for an instrument type.
        /// </summary>
        internal static string Enter4CharactersForSearch {
            get {
                return ResourceManager.GetString("Enter4CharactersForSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least 4 characters to search for an instrument type.
        /// </summary>
        internal static string Enter4CharactersForSearch_ {
            get {
                return ResourceManager.GetString("Enter4CharactersForSearch.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Lot number.
        /// </summary>
        internal static string EnterLot {
            get {
                return ResourceManager.GetString("EnterLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter production date.
        /// </summary>
        internal static string EnterProductionDate {
            get {
                return ResourceManager.GetString("EnterProductionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error code:.
        /// </summary>
        internal static string error_code_ {
            get {
                return ResourceManager.GetString("error code:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code :.
        /// </summary>
        internal static string Error_code__ {
            get {
                return ResourceManager.GetString("Error code :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to fetch instument info. Please try again!.
        /// </summary>
        internal static string ErrorGettingAssetInfo {
            get {
                return ResourceManager.GetString("ErrorGettingAssetInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error resetting tag..
        /// </summary>
        internal static string ErrorResettingTag {
            get {
                return ResourceManager.GetString("ErrorResettingTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Saved.
        /// </summary>
        internal static string File_Saved {
            get {
                return ResourceManager.GetString("File_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding Reader ....
        /// </summary>
        internal static string Finding_Reader____ {
            get {
                return ResourceManager.GetString("Finding Reader ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding RFID reader.
        /// </summary>
        internal static string FindingRFIDreader {
            get {
                return ResourceManager.GetString("FindingRFIDreader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred because the Firmware may be too old.
        /// </summary>
        internal static string Firmware_too_old_error {
            get {
                return ResourceManager.GetString("Firmware_too_old_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From ToDay.
        /// </summary>
        internal static string From_ToDay {
            get {
                return ResourceManager.GetString("From ToDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this does not solve the problem, contact Caretag support and report the error code..
        /// </summary>
        internal static string If_this_does_not_solve_the_problem__contact_Caretag_support_and_report_the_error_code_ {
            get {
                return ResourceManager.GetString("If this does not solve the problem, contact Caretag support and report the error " +
                        "code.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on &quot;Restart&quot; to scan a new RFID tag.
        /// </summary>
        internal static string InactiveAssetOptions {
            get {
                return ResourceManager.GetString("InactiveAssetOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information for ALL Users - Last 30 Days.
        /// </summary>
        internal static string Information_for_ALL_Users___Last_30_Days {
            get {
                return ResourceManager.GetString("Information for ALL Users & Last 30 Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information for User: .
        /// </summary>
        internal static string Information_for_User_ {
            get {
                return ResourceManager.GetString("Information for User:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrument saved!.
        /// </summary>
        internal static string InstrumentSaved {
            get {
                return ResourceManager.GetString("InstrumentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving instrument. Please try again!.
        /// </summary>
        internal static string InstrumentSaveError {
            get {
                return ResourceManager.GetString("InstrumentSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while searching for instrument type. Please try again!.
        /// </summary>
        internal static string InstrumentTypeSearchError {
            get {
                return ResourceManager.GetString("InstrumentTypeSearchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Already SENT to SERVICE !.
        /// </summary>
        internal static string Is_Already_SENT_to_SERVICE__ {
            get {
                return ResourceManager.GetString("Is Already SENT to SERVICE !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue ... Program will Not Work Correct !.
        /// </summary>
        internal static string Issue_____Program_will_Not_Work_Correct__ {
            get {
                return ResourceManager.GetString("Issue ... Program will Not Work Correct !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue in LogIn ... Try Again ! {0}{1}.
        /// </summary>
        internal static string Issue_in_LogIn_____Try_Again____0__1_ {
            get {
                return ResourceManager.GetString("Issue in LogIn ... Try Again ! {0}{1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue in Send To Service ... Please Report !.
        /// </summary>
        internal static string Issue_in_Send_To_Service_____Please_Report__ {
            get {
                return ResourceManager.GetString("Issue in Send To Service ... Please Report !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Read_SQLConnection... .
        /// </summary>
        internal static string Issue_Read_SQLConnection___ {
            get {
                return ResourceManager.GetString("Issue Read_SQLConnection...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastSeen Date.
        /// </summary>
        internal static string LastSeen_Date {
            get {
                return ResourceManager.GetString("LastSeen_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LastSeen Place.
        /// </summary>
        internal static string LastSeen_Place {
            get {
                return ResourceManager.GetString("LastSeen_Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Program Settings ....
        /// </summary>
        internal static string Loading_Program_Settings____ {
            get {
                return ResourceManager.GetString("Loading Program Settings ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred because the LogIn failed.
        /// </summary>
        internal static string LogIn_failed {
            get {
                return ResourceManager.GetString("LogIn failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot no.
        /// </summary>
        internal static string LotNo {
            get {
                return ResourceManager.GetString("LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing date.
        /// </summary>
        internal static string ManufacturingDate {
            get {
                return ResourceManager.GetString("ManufacturingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Service Vendor EXIST !   Please Correct.
        /// </summary>
        internal static string No_Service_Vendor_EXIST_____Please_Correct {
            get {
                return ResourceManager.GetString("No Service Vendor EXIST !   Please Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Update ....
        /// </summary>
        internal static string No_Update____ {
            get {
                return ResourceManager.GetString("No Update ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No reader found!.
        /// </summary>
        internal static string NoReaderFound {
            get {
                return ResourceManager.GetString("NoReaderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected....
        /// </summary>
        internal static string Not_Connected___ {
            get {
                return ResourceManager.GetString("Not Connected...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected to:.
        /// </summary>
        internal static string Not_Connected_to_ {
            get {
                return ResourceManager.GetString("Not Connected to:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tag found.
        /// </summary>
        internal static string NoTagFound {
            get {
                return ResourceManager.GetString("NoTagFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag matches GS1 prefix but is not recognized as an instrument or tray or container. Click on &quot;Link Asset&quot; to set asset type, or &quot;Restart&quot; to scan a new RFID tag..
        /// </summary>
        internal static string NotRecognizedPrefix {
            get {
                return ResourceManager.GetString("NotRecognizedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one tag should be on the reader. Remove any other tags from the reader area and try again..
        /// </summary>
        internal static string OnlyOneTagShouldBeOnTheReader {
            get {
                return ResourceManager.GetString("OnlyOneTagShouldBeOnTheReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pivot is Not Loading.
        /// </summary>
        internal static string Pivot_Not_Loading {
            get {
                return ResourceManager.GetString("Pivot_Not_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application..
        /// </summary>
        internal static string Please_restart_the_application_ {
            get {
                return ResourceManager.GetString("Please restart the application.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application and if this does not solve the problem, contact Caretag Support and report the Error Code.
        /// </summary>
        internal static string Please_restart_the_application_and_if_this_does_not_solve_the_problem__contact_Caretag_Support_and_report_the_Error_Code {
            get {
                return ResourceManager.GetString("Please restart the application and if this does not solve the problem, contact Ca" +
                        "retag Support and report the Error Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production date format is incorrect. .
        /// </summary>
        internal static string ProductionDateFormatIncorrect {
            get {
                return ResourceManager.GetString("ProductionDateFormatIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production date is in the future! Please enter a date in the past. .
        /// </summary>
        internal static string ProductionDateInFuture {
            get {
                return ResourceManager.GetString("ProductionDateInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read NEXT Instrument.
        /// </summary>
        internal static string Read_NEXT_Instrument {
            get {
                return ResourceManager.GetString("Read NEXT Instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader Is Correct Connected !.
        /// </summary>
        internal static string Reader_Is_Correct_Connected__ {
            get {
                return ResourceManager.GetString("Reader Is Correct Connected !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RFID tag has been successfully read, with the next details:.
        /// </summary>
        internal static string RfidSuccessfullyScanned {
            get {
                return ResourceManager.GetString("RfidSuccessfullyScanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules_Station.
        /// </summary>
        internal static string Rules_Station {
            get {
                return ResourceManager.GetString("Rules_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Folder .
        /// </summary>
        internal static string Select_the_Folder {
            get {
                return ResourceManager.GetString("Select the Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an instrument type..
        /// </summary>
        internal static string SelectInstrument {
            get {
                return ResourceManager.GetString("SelectInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this Instrument aside .....
        /// </summary>
        internal static string Set_this_Instrument_aside_____ {
            get {
                return ResourceManager.GetString("Set this Instrument aside ....", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software End_Of_Life (EOL) : {0}.
        /// </summary>
        internal static string Software_End_Of_Life__EOL_____0_ {
            get {
                return ResourceManager.GetString("Software End_Of_Life (EOL) : {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went very wrong ! .....
        /// </summary>
        internal static string Something_went_very_wrong_______ {
            get {
                return ResourceManager.GetString("Something went very wrong ! ....", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status for Sent To Service : .
        /// </summary>
        internal static string Status_for_Sent_To_Service__ {
            get {
                return ResourceManager.GetString("Status for Sent To Service :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status for Sent To Service : All Users.
        /// </summary>
        internal static string Status_for_Sent_To_Service___All_Users {
            get {
                return ResourceManager.GetString("Status for Sent To Service : All Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Overview for Rules : .
        /// </summary>
        internal static string Status_Overview_for_Rules__ {
            get {
                return ResourceManager.GetString("Status Overview for Rules :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterilization cart saved.
        /// </summary>
        internal static string SterilizationCartSaved {
            get {
                return ResourceManager.GetString("SterilizationCartSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully read tag!.
        /// </summary>
        internal static string SuccessfullyTag {
            get {
                return ResourceManager.GetString("SuccessfullyTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgical_TechnicalStation.
        /// </summary>
        internal static string Surgical_TechnicalStation {
            get {
                return ResourceManager.GetString("Surgical_TechnicalStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag does not match GS1 prefix. This is most likely because it is fresh from the factory and should be programmed. Click on &quot;Program Tag&quot; to program it..
        /// </summary>
        internal static string TagDoesNotMatchGS1Prefix {
            get {
                return ResourceManager.GetString("TagDoesNotMatchGS1Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag matches container in database. Click &apos;Finish&apos; to start over with another asset..
        /// </summary>
        internal static string TagMatchesContainer {
            get {
                return ResourceManager.GetString("TagMatchesContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag matches instrument in database:.
        /// </summary>
        internal static string TagMatchesInstrument {
            get {
                return ResourceManager.GetString("TagMatchesInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag matches tray in database. Click &apos;Finish&apos; to start over with another asset..
        /// </summary>
        internal static string TagMatchesTray {
            get {
                return ResourceManager.GetString("TagMatchesTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag has been programmed!.
        /// </summary>
        internal static string TagProgrammed {
            get {
                return ResourceManager.GetString("TagProgrammed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag has been reset..
        /// </summary>
        internal static string TagReset {
            get {
                return ResourceManager.GetString("TagReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Type.
        /// </summary>
        internal static string Technical_Type {
            get {
                return ResourceManager.GetString("Technical_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Station.
        /// </summary>
        internal static string TechnicalStation {
            get {
                return ResourceManager.GetString("TechnicalStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Instrument     MAY NOT    be Used  !.
        /// </summary>
        internal static string The_Instrument_____MAY_NOT____be_Used___ {
            get {
                return ResourceManager.GetString("The Instrument     MAY NOT    be Used  !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL_SERVER is NOT running .. Correct and try again !.
        /// </summary>
        internal static string The_SQL_SERVER_is_NOT_running____Correct_and_try_again__ {
            get {
                return ResourceManager.GetString("The SQL_SERVER is NOT running .. Correct and try again !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Station is NOT Recognized .. Check with Administrator and try again !.
        /// </summary>
        internal static string The_Station_is_NOT_Recognized____Check_with_Administrator_and_try_again__ {
            get {
                return ResourceManager.GetString("The Station is NOT Recognized .. Check with Administrator and try again !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is a Demand Service from :.
        /// </summary>
        internal static string There_Is_a_Demand_Service_from__ {
            get {
                return ResourceManager.GetString("There Is a Demand Service from :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tray saved!.
        /// </summary>
        internal static string TraySaved {
            get {
                return ResourceManager.GetString("TraySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgical trolley saved!.
        /// </summary>
        internal static string TrolleySaved {
            get {
                return ResourceManager.GetString("TrolleySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing to tag skipped when using simulator.
        /// </summary>
        internal static string WritingToTagSkippedWhenUsingSimulator {
            get {
                return ResourceManager.GetString("WritingToTagSkippedWhenUsingSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Not Exit -&gt; There is a Service Request !.
        /// </summary>
        internal static string You_Can_Not_Exit____There_is_a_Service_Request__ {
            get {
                return ResourceManager.GetString("You Can Not Exit -> There is a Service Request !", resourceCulture);
            }
        }
    }
}
