//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service_Station.My.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Service_Station.WinFormStrings", typeof(WinFormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All triggered rules (marked with red) must be accepted to accept item from service. .
        /// </summary>
        internal static string All_triggered_rules__marked_with_red__must_be_accepted_to_accept_item_from_service__ {
            get {
                return ResourceManager.GetString("All triggered rules (marked with red) must be accepted to accept item from servic" +
                        "e. ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Received from Service ! :.
        /// </summary>
        internal static string Already_Received_from_Service__ {
            get {
                return ResourceManager.GetString("Already Received from Service !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when loading the application. Please restart the application..
        /// </summary>
        internal static string An_error_occured_when_loading_the_application__Please_restart_the_application_ {
            get {
                return ResourceManager.GetString("An error occured when loading the application. Please restart the application.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured when loading the form.
        /// </summary>
        internal static string An_error_occured_when_loading_the_form {
            get {
                return ResourceManager.GetString("An error occured when loading the form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when loading the application. Please restart the application..
        /// </summary>
        internal static string An_error_occurred_when_loading_the_application__Please_restart_the_application_ {
            get {
                return ResourceManager.GetString("An error occurred when loading the application. Please restart the application.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when trying to connect to the database.
        /// </summary>
        internal static string An_error_occurred_when_trying_to_connect_to_the_database {
            get {
                return ResourceManager.GetString("An error occurred when trying to connect to the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while accepting the service.
        /// </summary>
        internal static string An_error_occurred_while_accepting_the_service {
            get {
                return ResourceManager.GetString("An error occurred while accepting the service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding periods.
        /// </summary>
        internal static string An_error_occurred_while_adding_periods {
            get {
                return ResourceManager.GetString("An error occurred while adding periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while changing the selected index.
        /// </summary>
        internal static string An_error_occurred_while_changing_the_selected_index {
            get {
                return ResourceManager.GetString("An error occurred while changing the selected index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while checking the rows of the data grid view.
        /// </summary>
        internal static string An_error_occurred_while_checking_the_rows_of_the_data_grid_view {
            get {
                return ResourceManager.GetString("An error occurred while checking the rows of the data grid view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while clicking a cell in the data grid view.
        /// </summary>
        internal static string An_error_occurred_while_clicking_a_cell_in_the_data_grid_view {
            get {
                return ResourceManager.GetString("An error occurred while clicking a cell in the data grid view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while clicking the check all button.
        /// </summary>
        internal static string An_error_occurred_while_clicking_the_check_all_button {
            get {
                return ResourceManager.GetString("An error occurred while clicking the check all button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while clicking the read instrument button.
        /// </summary>
        internal static string An_error_occurred_while_clicking_the_read_instrument_button {
            get {
                return ResourceManager.GetString("An error occurred while clicking the read instrument button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while clicking the reset button.
        /// </summary>
        internal static string An_error_occurred_while_clicking_the_reset_button {
            get {
                return ResourceManager.GetString("An error occurred while clicking the reset button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while coloring the data grid view rows.
        /// </summary>
        internal static string An_error_occurred_while_coloring_the_data_grid_view_rows {
            get {
                return ResourceManager.GetString("An error occurred while coloring the data grid view rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while filling the week combo box.
        /// </summary>
        internal static string An_error_occurred_while_filling_the_week_combo_box {
            get {
                return ResourceManager.GetString("An error occurred while filling the week combo box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while initializing the form.
        /// </summary>
        internal static string An_error_occurred_while_initializing_the_form {
            get {
                return ResourceManager.GetString("An error occurred while initializing the form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the page.
        /// </summary>
        internal static string An_error_occurred_while_loading_the_page {
            get {
                return ResourceManager.GetString("An error occurred while loading the page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the pivot data grid.
        /// </summary>
        internal static string An_error_occurred_while_loading_the_pivot_data_grid {
            get {
                return ResourceManager.GetString("An error occurred while loading the pivot data grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while logging the service into the database.
        /// </summary>
        internal static string An_error_occurred_while_logging_the_service_into_the_database {
            get {
                return ResourceManager.GetString("An error occurred while logging the service into the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while pressing the world picture.
        /// </summary>
        internal static string An_error_occurred_while_pressing_the_world_picture {
            get {
                return ResourceManager.GetString("An error occurred while pressing the world picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving information about the instrument.
        /// </summary>
        internal static string An_error_occurred_while_retrieving_information_about_the_instrument {
            get {
                return ResourceManager.GetString("An error occurred while retrieving information about the instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the scan log (scan event) in the database..
        /// </summary>
        internal static string An_error_occurred_while_saving_the_scan_log__scan_event__in_the_database_ {
            get {
                return ResourceManager.GetString("An error occurred while saving the scan log (scan event) in the database.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while sending the instrument to service.
        /// </summary>
        internal static string An_error_occurred_while_sending_the_instrument_to_service {
            get {
                return ResourceManager.GetString("An error occurred while sending the instrument to service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while showing the list view.
        /// </summary>
        internal static string An_error_occurred_while_showing_the_list_view {
            get {
                return ResourceManager.GetString("An error occurred while showing the list view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying fill the date boxes.
        /// </summary>
        internal static string An_error_occurred_while_trying_fill_the_date_boxes {
            get {
                return ResourceManager.GetString("An error occurred while trying fill the date boxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying fill the number boxes.
        /// </summary>
        internal static string An_error_occurred_while_trying_fill_the_number_boxes {
            get {
                return ResourceManager.GetString("An error occurred while trying fill the number boxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying fill the text boxes.
        /// </summary>
        internal static string An_error_occurred_while_trying_fill_the_text_boxes {
            get {
                return ResourceManager.GetString("An error occurred while trying fill the text boxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to change the selected index.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_change_the_selected_index {
            get {
                return ResourceManager.GetString("An error occurred while trying to change the selected index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to click the information button.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_click_the_information_button {
            get {
                return ResourceManager.GetString("An error occurred while trying to click the information button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to collapse or expand the pivot grid control rows.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_collapse_or_expand_the_pivot_grid_control_rows {
            get {
                return ResourceManager.GetString("An error occurred while trying to collapse or expand the pivot grid control rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to display a value in the pivot data grid.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_display_a_value_in_the_pivot_data_grid {
            get {
                return ResourceManager.GetString("An error occurred while trying to display a value in the pivot data grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to exit.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_exit {
            get {
                return ResourceManager.GetString("An error occurred while trying to exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to export the Excel.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_export_the_Excel {
            get {
                return ResourceManager.GetString("An error occurred while trying to export the Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to find the columns.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_find_the_columns {
            get {
                return ResourceManager.GetString("An error occurred while trying to find the columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to load the CSSD information.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_load_the_CSSD_information {
            get {
                return ResourceManager.GetString("An error occurred while trying to load the CSSD information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to load the pivot grid.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_load_the_pivot_grid {
            get {
                return ResourceManager.GetString("An error occurred while trying to load the pivot grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to LogIn.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_LogIn {
            get {
                return ResourceManager.GetString("An error occurred while trying to LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to make the service table.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_make_the_service_table {
            get {
                return ResourceManager.GetString("An error occurred while trying to make the service table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to print the report.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_print_the_report {
            get {
                return ResourceManager.GetString("An error occurred while trying to print the report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to read the next instrument.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_read_the_next_instrument {
            get {
                return ResourceManager.GetString("An error occurred while trying to read the next instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to report.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_report {
            get {
                return ResourceManager.GetString("An error occurred while trying to report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to retrieve the ID for the LogIn.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_retrieve_the_ID_for_the_LogIn {
            get {
                return ResourceManager.GetString("An error occurred while trying to retrieve the ID for the LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to retrieve the vendor service information.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_retrieve_the_vendor_service_information {
            get {
                return ResourceManager.GetString("An error occurred while trying to retrieve the vendor service information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to save the Log in the database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_save_the_Log_in_the_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to save the Log in the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to send the instrument out.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_send_the_instrument_out {
            get {
                return ResourceManager.GetString("An error occurred while trying to send the instrument out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to set up the data grid view.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_set_up_the_data_grid_view {
            get {
                return ResourceManager.GetString("An error occurred while trying to set up the data grid view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to update the instrument service information.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_update_the_instrument_service_information {
            get {
                return ResourceManager.GetString("An error occurred while trying to update the instrument service information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to update the tag information.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_update_the_tag_information {
            get {
                return ResourceManager.GetString("An error occurred while trying to update the tag information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to write to the database.
        /// </summary>
        internal static string An_error_occurred_while_trying_to_write_to_the_database {
            get {
                return ResourceManager.GetString("An error occurred while trying to write to the database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the maintenance.
        /// </summary>
        internal static string An_error_occurred_while_updating_the_maintenance {
            get {
                return ResourceManager.GetString("An error occurred while updating the maintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while writing the service.
        /// </summary>
        internal static string An_error_occurred_while_writing_the_service {
            get {
                return ResourceManager.GetString("An error occurred while writing the service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be aware NO Reader can be Found ! .....
        /// </summary>
        internal static string Be_aware_NO_Reader_can_be_Found_______ {
            get {
                return ResourceManager.GetString("Be aware NO Reader can be Found ! ....", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Version Or License  - An Issue !.
        /// </summary>
        internal static string Check_Version_Or_License____An_Issue__ {
            get {
                return ResourceManager.GetString("Check Version Or License  - An Issue !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Dot Net Version ....
        /// </summary>
        internal static string Checking_Dot_Net_Version____ {
            get {
                return ResourceManager.GetString("Checking Dot Net Version ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for Update ! .
        /// </summary>
        internal static string Checking_for_Update__ {
            get {
                return ResourceManager.GetString("Checking for Update !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Reader_ID ....
        /// </summary>
        internal static string Checking_Reader_ID____ {
            get {
                return ResourceManager.GetString("Checking Reader_ID ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Version &amp; License ....
        /// </summary>
        internal static string Checking_Version___License____ {
            get {
                return ResourceManager.GetString("Checking Version & License ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected....
        /// </summary>
        internal static string Connected___ {
            get {
                return ResourceManager.GetString("Connected...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to SQL_SERVER:.
        /// </summary>
        internal static string Connecting_to_SQL_SERVER_ {
            get {
                return ResourceManager.GetString("Connecting to SQL_SERVER:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to SQL_SERVER ... .
        /// </summary>
        internal static string Connecting_to_SQL_SERVER____ {
            get {
                return ResourceManager.GetString("Connecting to SQL_SERVER ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact IT department Or Caretag !.
        /// </summary>
        internal static string Contact_IT_department_Or_Caretag__ {
            get {
                return ResourceManager.GetString("Contact IT department Or Caretag !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Issue and Program is Shutting Down.
        /// </summary>
        internal static string Correct_Issue_and_Program_is_Shutting_Down {
            get {
                return ResourceManager.GetString("Correct Issue and Program is Shutting Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days from Demand Service : .
        /// </summary>
        internal static string Days_from_Demand {
            get {
                return ResourceManager.GetString("Days from Demand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days from Sent To Service: .
        /// </summary>
        internal static string Days_from_Sent_To_Service {
            get {
                return ResourceManager.GetString("Days from Sent To Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days In Service.
        /// </summary>
        internal static string Days_In_Service {
            get {
                return ResourceManager.GetString("Days In Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Configuration Used - Reader ID:.
        /// </summary>
        internal static string Default_Configuration_Used___Reader_ID_ {
            get {
                return ResourceManager.GetString("Default Configuration Used - Reader ID:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Service at : .
        /// </summary>
        internal static string Demand_Service {
            get {
                return ResourceManager.GetString("Demand Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand Service from Date: .
        /// </summary>
        internal static string Demand_Service_from_Date {
            get {
                return ResourceManager.GetString("Demand Service from Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot Net Version ... is NOT Okay.
        /// </summary>
        internal static string Dot_Net_Version_____is_NOT_Okay {
            get {
                return ResourceManager.GetString("Dot Net Version ... is NOT Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dot Net Version ... Is Okay.
        /// </summary>
        internal static string Dot_Net_Version_____Is_Okay {
            get {
                return ResourceManager.GetString("Dot Net Version ... Is Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error code:.
        /// </summary>
        internal static string error_code_ {
            get {
                return ResourceManager.GetString("error code:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code :.
        /// </summary>
        internal static string Error_code__ {
            get {
                return ResourceManager.GetString("Error code :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finding Reader ....
        /// </summary>
        internal static string Finding_Reader____ {
            get {
                return ResourceManager.GetString("Finding Reader ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has Not been Ordered - Has It been Done ?.
        /// </summary>
        internal static string has_Not_been_Ordered___Has_It_been_Done__ {
            get {
                return ResourceManager.GetString("has Not been Ordered - Has It been Done ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this does not solve the problem, contact Caretag support and report the error code..
        /// </summary>
        internal static string If_this_does_not_solve_the_problem__contact_Caretag_support_and_report_the_error_code_ {
            get {
                return ResourceManager.GetString("If this does not solve the problem, contact Caretag support and report the error " +
                        "code.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Already SENT to SERVICE !.
        /// </summary>
        internal static string Is_Already_SENT_to_SERVICE__ {
            get {
                return ResourceManager.GetString("Is Already SENT to SERVICE !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue ... Program will Not Work Correct !.
        /// </summary>
        internal static string Issue_____Program_will_Not_Work_Correct__ {
            get {
                return ResourceManager.GetString("Issue ... Program will Not Work Correct !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue in LogIn ... Try Again ! {0}{1}.
        /// </summary>
        internal static string Issue_in_LogIn_____Try_Again____0__1_ {
            get {
                return ResourceManager.GetString("Issue in LogIn ... Try Again ! {0}{1}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue in Send To Service ... Please Report !.
        /// </summary>
        internal static string Issue_in_Send_To_Service_____Please_Report__ {
            get {
                return ResourceManager.GetString("Issue in Send To Service ... Please Report !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue No Rules Exist - Please Report !.
        /// </summary>
        internal static string Issue_No_Rules_Exist___Please_Report__ {
            get {
                return ResourceManager.GetString("Issue No Rules Exist - Please Report !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Read_SQLConnection... .
        /// </summary>
        internal static string Issue_Read_SQLConnection___ {
            get {
                return ResourceManager.GetString("Issue Read_SQLConnection...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Service.
        /// </summary>
        internal static string Last_Service {
            get {
                return ResourceManager.GetString("Last Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Program Settings ....
        /// </summary>
        internal static string Loading_Program_Settings____ {
            get {
                return ResourceManager.GetString("Loading Program Settings ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Periods.
        /// </summary>
        internal static string Maintenance_Periods {
            get {
                return ResourceManager.GetString("Maintenance Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Text.
        /// </summary>
        internal static string Maintenance_Text {
            get {
                return ResourceManager.GetString("Maintenance Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance Value.
        /// </summary>
        internal static string Maintenance_Value {
            get {
                return ResourceManager.GetString("Maintenance Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Service Vendor EXIST !   Please Correct.
        /// </summary>
        internal static string No_Service_Vendor_EXIST_____Please_Correct {
            get {
                return ResourceManager.GetString("No Service Vendor EXIST !   Please Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Update ....
        /// </summary>
        internal static string No_Update____ {
            get {
                return ResourceManager.GetString("No Update ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all rules accepted.
        /// </summary>
        internal static string Not_all_rules_accepted {
            get {
                return ResourceManager.GetString("Not all rules accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected....
        /// </summary>
        internal static string Not_Connected___ {
            get {
                return ResourceManager.GetString("Not Connected...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected to:.
        /// </summary>
        internal static string Not_Connected_to_ {
            get {
                return ResourceManager.GetString("Not Connected to:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Service.
        /// </summary>
        internal static string Number_Service {
            get {
                return ResourceManager.GetString("Number Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pivot_Not_Loading.
        /// </summary>
        internal static string Pivot_Not_Loading {
            get {
                return ResourceManager.GetString("Pivot_Not_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the application..
        /// </summary>
        internal static string Please_restart_the_application_ {
            get {
                return ResourceManager.GetString("Please restart the application.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read NEXT Instrument.
        /// </summary>
        internal static string Read_NEXT_Instrument {
            get {
                return ResourceManager.GetString("Read NEXT Instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return From Service.
        /// </summary>
        internal static string Return_From_Service {
            get {
                return ResourceManager.GetString("Return From Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent To Service.
        /// </summary>
        internal static string Sent_To_Service {
            get {
                return ResourceManager.GetString("Sent To Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent To Service at Date: .
        /// </summary>
        internal static string Sent_To_Service_at_Date {
            get {
                return ResourceManager.GetString("Sent To Service at Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Counter.
        /// </summary>
        internal static string Service_Counter {
            get {
                return ResourceManager.GetString("Service Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service_Station.
        /// </summary>
        internal static string Service_Station {
            get {
                return ResourceManager.GetString("Service_Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Vendor.
        /// </summary>
        internal static string Service_Vendor {
            get {
                return ResourceManager.GetString("Service Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this Instrument aside .....
        /// </summary>
        internal static string Set_this_Instrument_aside_____ {
            get {
                return ResourceManager.GetString("Set this Instrument aside ....", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software End_Of_Life (EOL) : {0}.
        /// </summary>
        internal static string Software_End_Of_Life__EOL_____0_ {
            get {
                return ResourceManager.GetString("Software End_Of_Life (EOL) : {0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went very wrong ! .....
        /// </summary>
        internal static string Something_went_very_wrong_______ {
            get {
                return ResourceManager.GetString("Something went very wrong ! ....", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status for Sent To Service : .
        /// </summary>
        internal static string Status_for_Sent_To_Service__ {
            get {
                return ResourceManager.GetString("Status for Sent To Service :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status for Sent To Service : All Users.
        /// </summary>
        internal static string Status_for_Sent_To_Service___All_Users {
            get {
                return ResourceManager.GetString("Status for Sent To Service : All Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Overview for Rules : .
        /// </summary>
        internal static string Status_Overview_for_Rules__ {
            get {
                return ResourceManager.GetString("Status Overview for Rules :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Instrument     MAY NOT    be Used  !.
        /// </summary>
        internal static string The_Instrument_____MAY_NOT____be_Used___ {
            get {
                return ResourceManager.GetString("The Instrument     MAY NOT    be Used  !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SQL_SERVER is NOT running .. Correct and try again !.
        /// </summary>
        internal static string The_SQL_SERVER_is_NOT_running____Correct_and_try_again__ {
            get {
                return ResourceManager.GetString("The SQL_SERVER is NOT running .. Correct and try again !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Station is NOT Recognized .. Check with Administrator and try again !.
        /// </summary>
        internal static string The_Station_is_NOT_Recognized____Check_with_Administrator_and_try_again__ {
            get {
                return ResourceManager.GetString("The Station is NOT Recognized .. Check with Administrator and try again !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Is a Demand Service from :.
        /// </summary>
        internal static string There_Is_a_Demand_Service_from__ {
            get {
                return ResourceManager.GetString("There Is a Demand Service from :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Part of The Service:.
        /// </summary>
        internal static string This_Part_of_The_Service_ {
            get {
                return ResourceManager.GetString("This Part of The Service:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can Not Exit -&gt; There is a Service Request !.
        /// </summary>
        internal static string You_Can_Not_Exit____There_is_a_Service_Request__ {
            get {
                return ResourceManager.GetString("You Can Not Exit -> There is a Service Request !", resourceCulture);
            }
        }
    }
}
