//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminStation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinFormStrings_de_DE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinFormStrings_de_DE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminStation.WinFormStrings.de-DE", typeof(WinFormStrings_de_DE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Zu Datentabelle hinzugefügt.. .
        /// </summary>
        internal static string _Added_to_DataTable__ {
            get {
                return ResourceManager.GetString(".Added to DataTable..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Backup...
        /// </summary>
        internal static string _Back_Up__ {
            get {
                return ResourceManager.GetString(".Back Up..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Backup-FEHLER ...
        /// </summary>
        internal static string _Back_Up_ERROR__ {
            get {
                return ResourceManager.GetString(".Back Up ERROR..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Datentabelle überschrieben...
        /// </summary>
        internal static string _DataTable_Overwritten__ {
            get {
                return ResourceManager.GetString(".DataTable Overwritten..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Abschließen...
        /// </summary>
        internal static string _Finish__ {
            get {
                return ResourceManager.GetString(".Finish..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .FEHLER...
        /// </summary>
        internal static string _In_ERROR__ {
            get {
                return ResourceManager.GetString(".In ERROR..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Vorgang abbrechen ...
        /// </summary>
        internal static string _Operation_Cancel__ {
            get {
                return ResourceManager.GetString(".Operation Cancel..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Vorgang GESTOPPT ...
        /// </summary>
        internal static string _Operation_STOPPED__ {
            get {
                return ResourceManager.GetString(".Operation STOPPED..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zur Datenbanktabelle hinzugefügt: ...
        /// </summary>
        internal static string Added_Database {
            get {
                return ResourceManager.GetString("Added_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Zur Datenbank hinzugefügt... .
        /// </summary>
        internal static string Added_to_DataTable___ {
            get {
                return ResourceManager.GetString("Added to DataTable...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie, dass ALLE GLEICHEN Typen vorhandener Tags geändert werden?.
        /// </summary>
        internal static string All_Same_Changed {
            get {
                return ResourceManager.GetString("All_Same_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass KEINE Kostenstelle verwendet werden soll?.
        /// </summary>
        internal static string Are_You_Sure_that_there_should__NOT_to_use_COST_Center__ {
            get {
                return ResourceManager.GetString("Are You Sure that there should  NOT to use COST Center ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie den Text für die Tabelle in UPPER ändern möchten : .
        /// </summary>
        internal static string Are_You_Sure_that_you_will_Change_Text_To_UPPER_for_Table_ {
            get {
                return ResourceManager.GetString("Are You Sure that you will Change Text To UPPER for Table:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie Tabellen mit demselben Text und korrekter Rechtschreibung korrigieren möchten?.
        /// </summary>
        internal static string Are_You_Sure_that_you_will_Correct_Tables_with_Same_Text_and_Correct_Spelling__ {
            get {
                return ResourceManager.GetString("Are You Sure that you will Correct Tables with Same Text and Correct Spelling ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie die RFID-Karte LÖSCHEN möchten?.
        /// </summary>
        internal static string Are_You_Sure_You_want_to_DELETE_RFID_Card__ {
            get {
                return ResourceManager.GetString("Are You Sure You want to DELETE RFID Card ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie den Benutzer LÖSCHEN möchten?.
        /// </summary>
        internal static string Are_You_Sure_You_want_to_DELETE_User__ {
            get {
                return ResourceManager.GetString("Are You Sure You want to DELETE User ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereichsbeschreibung:.
        /// </summary>
        internal static string Area_Description_ {
            get {
                return ResourceManager.GetString("Area_Description:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereichsname:.
        /// </summary>
        internal static string Area_Name_ {
            get {
                return ResourceManager.GetString("Area Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup-Datei : .
        /// </summary>
        internal static string BackUp_ {
            get {
                return ResourceManager.GetString("BackUp:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BACKUP fertiggestellt.
        /// </summary>
        internal static string BACKUP_DONE {
            get {
                return ResourceManager.GetString("BACKUP DONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Großes Problem...Wenden Sie sich an den Administrator und versuchen Sie es erneut!.
        /// </summary>
        internal static string Big_Issue___Check_with_Administrator_and_try_again__ {
            get {
                return ResourceManager.GetString("Big Issue ..Check with Administrator and try again !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei kann NICHT importiert werden ... Die Spalten sind nicht IDENTISCH. Siehe Spalte: .
        /// </summary>
        internal static string Can_NOT_import_file_____The_columns_are_Not_IDENTICAL_See_Column_ {
            get {
                return ResourceManager.GetString("Can NOT import file ... The columns are Not IDENTICAL See Column:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorgang abbrechen?.
        /// </summary>
        internal static string Cancel_this_operation_ {
            get {
                return ResourceManager.GetString("Cancel this operation?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALLE Tags geändert - Bitte haben Sie Verständnis!.
        /// </summary>
        internal static string Changed_All_Tags {
            get {
                return ResourceManager.GetString("Changed_All_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text wechseln.
        /// </summary>
        internal static string Changing_Text {
            get {
                return ResourceManager.GetString("Changing Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK Blattname is &apos;Sheet1&apos; und Column_Names are A-B-C-D !.
        /// </summary>
        internal static string Check_Sheet {
            get {
                return ResourceManager.GetString("Check_Sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfen Sie, ob es sich um den richtigen Eintrag handelt! .
        /// </summary>
        internal static string Check_that_it_is_the_Correct_Record__ {
            get {
                return ResourceManager.GetString("Check that it is the Correct Record !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfen der Dot-Net-Version...
        /// </summary>
        internal static string Checking_Dot_Net_Version___ {
            get {
                return ResourceManager.GetString("Checking Dot Net Version ..", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auf Aktualisierungen prüfen! .
        /// </summary>
        internal static string Checking_for_Update__ {
            get {
                return ResourceManager.GetString("Checking for Update !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leser_ID wird überprüft ....
        /// </summary>
        internal static string Checking_Reader_ID____ {
            get {
                return ResourceManager.GetString("Checking Reader_ID ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software wird geprüft ....
        /// </summary>
        internal static string Checking_Software____ {
            get {
                return ResourceManager.GetString("Checking Software ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version &amp; Lizenz werden geprüft ....
        /// </summary>
        internal static string Checking_Version___License____ {
            get {
                return ResourceManager.GetString("Checking Version & License ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID zum Löschen auswählen.
        /// </summary>
        internal static string Choose_RFID_to_Delete {
            get {
                return ResourceManager.GetString("Choose RFID to Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgewählte Tabletts: .
        /// </summary>
        internal static string Chosen_Trays_ {
            get {
                return ResourceManager.GetString("Chosen Trays:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung zum SQL-SERVER ....
        /// </summary>
        internal static string Connecting_to_SQL_SERVER____ {
            get {
                return ResourceManager.GetString("Connecting to SQL_SERVER ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator kontaktieren.
        /// </summary>
        internal static string Contact_Admin {
            get {
                return ResourceManager.GetString("Contact_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrigieren Sie und versuchen Sie es erneut.
        /// </summary>
        internal static string Correct_Again {
            get {
                return ResourceManager.GetString("Correct_Again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korrigieren oder mit ESC abbrechen!.
        /// </summary>
        internal static string Correct_ESC {
            get {
                return ResourceManager.GetString("Correct_ESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kostenstelle.
        /// </summary>
        internal static string Cost_Center {
            get {
                return ResourceManager.GetString("Cost_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kostenstellen-ID.
        /// </summary>
        internal static string Cost_Center_ID {
            get {
                return ResourceManager.GetString("Cost_Center_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kostenstelle verwendet.
        /// </summary>
        internal static string Cost_Center_In_Use {
            get {
                return ResourceManager.GetString("Cost_Center In Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kostenstelle nicht verwendet.
        /// </summary>
        internal static string Cost_Center_Not_Used {
            get {
                return ResourceManager.GetString("Cost_Center Not Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl: .
        /// </summary>
        internal static string Count_ {
            get {
                return ResourceManager.GetString("Count:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzerfehler beim Erstellen eines Kontakts -&gt; Caretag!.
        /// </summary>
        internal static string Creating_User_Failed_Contact_____Caretag__ {
            get {
                return ResourceManager.GetString("Creating User Failed Contact ->  Caretag !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV-Datei_gespeichert .
        /// </summary>
        internal static string CSV_File_Saved {
            get {
                return ResourceManager.GetString("CSV_File_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum geändert.
        /// </summary>
        internal static string Date_Changed {
            get {
                return ResourceManager.GetString("Date_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  RFID-Benutzerkarte LÖSCHEN .
        /// </summary>
        internal static string DELETE_RFID_User_Card {
            get {
                return ResourceManager.GetString("DELETE RFID User Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablett gelöscht.
        /// </summary>
        internal static string Deleted_Tray {
            get {
                return ResourceManager.GetString("Deleted_Tray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dateien werden gelöscht.
        /// </summary>
        internal static string Deleting_Files {
            get {
                return ResourceManager.GetString("Deleting Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer wird gelöscht.
        /// </summary>
        internal static string Deleting_User {
            get {
                return ResourceManager.GetString("Deleting User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leere Datei: .
        /// </summary>
        internal static string Empty_File_ {
            get {
                return ResourceManager.GetString("Empty File:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leere Datei - Stellen Sie sicher, dass die Datei NICHT geöffnet ist.
        /// </summary>
        internal static string Empty_File___Check_File_NOT_is_Open {
            get {
                return ResourceManager.GetString("Empty File - Check File NOT is Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EPC-Länge muss GERADE sein! &quot; &amp; &quot;Diese Konfiguration nicht verwenden - Crashing Technical Station.
        /// </summary>
        internal static string EPC_Length_must_be_EVEN_______Do_Not_Use_This_Configuration___Crashing_Technical_Station {
            get {
                return ResourceManager.GetString("EPC Length must be EVEN !\" & \"Do Not Use This Configuration - Crashing Technical " +
                        "Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler im Parser-Befehl - Tabelle prüfen.
        /// </summary>
        internal static string Error_in_the_Parser_command___Check_Table {
            get {
                return ResourceManager.GetString("Error in the Parser command - Check Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FEHLER in RowCount_DataGridview!.
        /// </summary>
        internal static string Error_RowCount {
            get {
                return ResourceManager.GetString("Error_RowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler in der SQL-Anweisung:.
        /// </summary>
        internal static string Error_SQL {
            get {
                return ResourceManager.GetString("Error_SQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler:.
        /// </summary>
        internal static string Error_txt {
            get {
                return ResourceManager.GetString("Error_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stellen Sie die Synchronisation zwischen Checkboxes IN / OUT her.
        /// </summary>
        internal static string Establish_Synchronization_between_Check_Boxes_IN_OUT {
            get {
                return ResourceManager.GetString("Establish Synchronization between Check_Boxes IN/OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Läuft laut Vertrag aus .
        /// </summary>
        internal static string Expires {
            get {
                return ResourceManager.GetString("Expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei wird NICHT gespeichert:.
        /// </summary>
        internal static string File_Not_Saved {
            get {
                return ResourceManager.GetString("File_Not_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel-Datei wird gespeichert!.
        /// </summary>
        internal static string File_Saved {
            get {
                return ResourceManager.GetString("File_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endgültiges Prüfergebnis: {0} Originalkatalogelemente: {1}{0} Neue Elemente: {2}{0}{0} Überprüfen und bereit zum Aktualisieren?.
        /// </summary>
        internal static string Final_Check_Result___0__Original_Catalog_Items___1__0__New_Items___2__0__0_Check_and_ready_to_Update__ {
            get {
                return ResourceManager.GetString("Final Check Result: {0} Original Catalog Items: {1}{0} New Items: {2}{0}{0}Check " +
                        "and ready to Update ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reader suchen....
        /// </summary>
        internal static string Finding_Reader____ {
            get {
                return ResourceManager.GetString("Finding Reader ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gefunden: .
        /// </summary>
        internal static string Found__ {
            get {
                return ResourceManager.GetString("Found :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Aus Bereich:  .
        /// </summary>
        internal static string From_Area_ {
            get {
                return ResourceManager.GetString("From Area:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereit für importierte Anzahl der Zeilen (Instrumente):.
        /// </summary>
        internal static string Import_Rows {
            get {
                return ResourceManager.GetString("Import_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einfügen für ALLE fehlgeschlagen.
        /// </summary>
        internal static string Insert_Failed {
            get {
                return ResourceManager.GetString("Insert_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrumente: {0:N0}.
        /// </summary>
        internal static string Instruments___0_N0_ {
            get {
                return ResourceManager.GetString("Instruments: {0:N0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP-Adresse:   .
        /// </summary>
        internal static string IP_Adress_ {
            get {
                return ResourceManager.GetString("IP Adress:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem-ID .
        /// </summary>
        internal static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem ... Programm funktioniert nicht richtig!.
        /// </summary>
        internal static string Issue_____Program_will_Not_Work_Correct__ {
            get {
                return ResourceManager.GetString("Issue ... Program will Not Work Correct !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem bei der Zellvalidierung!.
        /// </summary>
        internal static string Issue_Cell_VAl {
            get {
                return ResourceManager.GetString("Issue_Cell_VAl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem bei der Aktualisierung!.
        /// </summary>
        internal static string Issue_Updating {
            get {
                return ResourceManager.GetString("Issue_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letzte 3 Monate.
        /// </summary>
        internal static string Last_3_Month {
            get {
                return ResourceManager.GetString("Last 3 Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmeinstellungen laden ....
        /// </summary>
        internal static string Loading_Program_Settings____ {
            get {
                return ResourceManager.GetString("Loading Program Settings ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Daten in Datei: .
        /// </summary>
        internal static string No_Data_in_File_ {
            get {
                return ResourceManager.GetString("No Data in File:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Daten in Datei - Datei prüfen.
        /// </summary>
        internal static string No_Data_in_File___Check_File {
            get {
                return ResourceManager.GetString("No Data in File - Check File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KEINE Datei oder Bereich ausgewählt -&gt; Abbrechen oder Datei auswählen!.
        /// </summary>
        internal static string NO_File_selected____Cancel_or_Select_File__ {
            get {
                return ResourceManager.GetString("NO File selected -> Cancel or Select File !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt KEINE ODBC-System deklarierten Verbindungen!.
        /// </summary>
        internal static string No_ODBC {
            get {
                return ResourceManager.GetString("No_ODBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Update ....
        /// </summary>
        internal static string No_Update____ {
            get {
                return ResourceManager.GetString("No Update ...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Datei oder Bereich ausgewählt -&gt; Abbrechen oder Datei auswählen!.
        /// </summary>
        internal static string NoFile_selected {
            get {
                return ResourceManager.GetString("NoFile_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen von Daten in der Tabelle NICHT erlauben - nur Daten HINZUFÜGEN!.
        /// </summary>
        internal static string NOT_Allow_to_delete_data_in_Table___Only_ADD_data__ {
            get {
                return ResourceManager.GetString("NOT Allow to delete data in Table - Only ADD data !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung zum SQL-konnte nicht hergestellt werden! -&gt; STOPPEN.
        /// </summary>
        internal static string Not_Conn_Server {
            get {
                return ResourceManager.GetString("Not_Conn_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Daten liegen NICHT im richtigen Format vor.
        /// </summary>
        internal static string Not_Correct_Format {
            get {
                return ResourceManager.GetString("Not_Correct_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen von Daten in der Tabelle NICHT erlauben - nur Daten HINZUFÜGEN!.
        /// </summary>
        internal static string Not_Delete {
            get {
                return ResourceManager.GetString("Not_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten konnten in DataGridview nicht gefiltert werden!.
        /// </summary>
        internal static string Not_Filter_Gridview {
            get {
                return ResourceManager.GetString("Not_Filter_Gridview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NICHT gefunden: .
        /// </summary>
        internal static string NOT_Found__ {
            get {
                return ResourceManager.GetString("NOT Found :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kann Datei NICHT importieren, Problem nicht bekannt:.
        /// </summary>
        internal static string Not_Import_File {
            get {
                return ResourceManager.GetString("Not_Import_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Katalog kann nicht importiert werden, da identische DATEN in der ersten Spalte vorhanden sind:.
        /// </summary>
        internal static string Not_Import_Identical_Data {
            get {
                return ResourceManager.GetString("Not_Import_Identical_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten konnten nicht in Gridview geladen werden.
        /// </summary>
        internal static string Not_Load_Gridview {
            get {
                return ResourceManager.GetString("Not_Load_Gridview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOSTENSTELLE NICHT verwenden.
        /// </summary>
        internal static string NOT_use_COST_Center {
            get {
                return ResourceManager.GetString("NOT use COST Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Checkbox_OR_IN: {0:N0}.
        /// </summary>
        internal static string Number_Of_CheckBox_OR_IN___0_N0_ {
            get {
                return ResourceManager.GetString("Number Of CheckBox_OR_IN: {0:N0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl Checkbox_SPD: {0:N0}.
        /// </summary>
        internal static string Number_Of_CheckBox_SPD___0_N0_ {
            get {
                return ResourceManager.GetString("Number Of CheckBox_SPD: {0:N0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der Instrumente in der Datenbank: .
        /// </summary>
        internal static string Number_off_instruments_in_Database_ {
            get {
                return ResourceManager.GetString("Number off instruments in Database:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klicken Sie auf OK, um zu speichern.
        /// </summary>
        internal static string OK_Save {
            get {
                return ResourceManager.GetString("OK_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Daten sollten NUR DOPPELTE enthalten.
        /// </summary>
        internal static string Only_Double {
            get {
                return ResourceManager.GetString("Only_Double", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Daten sollten NUR Integer-Werte/Zahlen enthalten.
        /// </summary>
        internal static string Only_Integer {
            get {
                return ResourceManager.GetString("Only_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Programm kann nur als eine Instanz ausgeführt werden!.
        /// </summary>
        internal static string Only_One {
            get {
                return ResourceManager.GetString("Only_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Daten sollten NUR Zeichenfolgen/Buchstaben enthalten.
        /// </summary>
        internal static string Only_Strings {
            get {
                return ResourceManager.GetString("Only_Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Nur bei aktivierter Kostenstelle! .
        /// </summary>
        internal static string Only_when_Cost_Center_is_Activated__ {
            get {
                return ResourceManager.GetString("Only when Cost Center is Activated !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übersicht für Instrument mit Bild.
        /// </summary>
        internal static string Overview_For_Instrument_With_Image {
            get {
                return ResourceManager.GetString("Overview For Instrument With Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übersicht Für Instrument ohne Bild.
        /// </summary>
        internal static string Overview_For_Instrument_with_No_Image {
            get {
                return ResourceManager.GetString("Overview For Instrument with No Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pivot-Datentabelle wird NICHT geladen.
        /// </summary>
        internal static string Pivot_Not_Loading {
            get {
                return ResourceManager.GetString("Pivot_Not_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei Zweifeln bitte KEINE ÄNDERUNGEN vornehmen - dies ist eine grundlegende Änderung des Systems! -&gt; Fortfahren ja? .
        /// </summary>
        internal static string Please_DO_NOT_Change_if_you_are_in_Doubt___This_is_a_Fundamental_change_to_System______Continue_Yes__ {
            get {
                return ResourceManager.GetString("Please DO NOT Change if you are in Doubt - This is a Fundamental change to System" +
                        " ! -> Continue Yes ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie die Daten drucken - ?.
        /// </summary>
        internal static string Print_Data {
            get {
                return ResourceManager.GetString("Print_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem ... Korrigieren Sie die Eingabedatei für fehlende-falsche DatumUhrzeit-Angabe in Spalte:.
        /// </summary>
        internal static string Problem_DateTime {
            get {
                return ResourceManager.GetString("Problem_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem beim LÖSCHEN von Daten: .
        /// </summary>
        internal static string Problem_DELETING_data_ {
            get {
                return ResourceManager.GetString("Problem DELETING data:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem beim Aktualisieren der Tabelle .
        /// </summary>
        internal static string Problem_in_Update_Table {
            get {
                return ResourceManager.GetString("Problem in Update Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem ... Eingabedatei korrigieren:.
        /// </summary>
        internal static string Problem_InputFile {
            get {
                return ResourceManager.GetString("Problem_InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem beim Laden der Tabelle aus der Datenbank.
        /// </summary>
        internal static string Problem_Loading {
            get {
                return ResourceManager.GetString("Problem_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem beim ÜBERSCHREIBEN von Daten: .
        /// </summary>
        internal static string Problem_OVERWRITING_data_ {
            get {
                return ResourceManager.GetString("Problem OVERWRITING data:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem mit dem Tabellennamen.
        /// </summary>
        internal static string Problem_Table {
            get {
                return ResourceManager.GetString("Problem_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prozedur-ID.
        /// </summary>
        internal static string Procedure_ID {
            get {
                return ResourceManager.GetString("Procedure_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prozedurbezeichnung.
        /// </summary>
        internal static string Procedure_Name {
            get {
                return ResourceManager.GetString("Procedure_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bereit zum Aktualisieren?.
        /// </summary>
        internal static string Ready_to_Update__ {
            get {
                return ResourceManager.GetString("Ready to Update ?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchten Sie es automatisiert ENTFERNEN? .
        /// </summary>
        internal static string Remove_Automated {
            get {
                return ResourceManager.GetString("Remove_Automated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronisation zwischen Check_Boxes IN / OUT aufheben.
        /// </summary>
        internal static string Remove_Synchronization_between_Check_Boxes_IN_OUT {
            get {
                return ResourceManager.GetString("Remove Synchronization between Check_Boxes IN/OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem melden - Unerwarteter Rückgabewert.
        /// </summary>
        internal static string Report_Problem {
            get {
                return ResourceManager.GetString("Report_Problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rückgabewert: Ladedaten importieren: .
        /// </summary>
        internal static string Return_value__ImportLoadData_ {
            get {
                return ResourceManager.GetString("Return value: ImportLoadData:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GESPEICHERT AM: .
        /// </summary>
        internal static string SAVED_AT_ {
            get {
                return ResourceManager.GetString("SAVED AT:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicherheitsstufe fehlgeschlagen: .
        /// </summary>
        internal static string Security_Level_Failed_ {
            get {
                return ResourceManager.GetString("Security Level Failed:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stufe einstellen fehlgeschlagen:  .
        /// </summary>
        internal static string Setting__Level__Failed_ {
            get {
                return ResourceManager.GetString("Setting  Level  Failed:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Softwarename.
        /// </summary>
        internal static string Software_Name {
            get {
                return ResourceManager.GetString("Software_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin_Manual.PDF befindet sich NICHT in:.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler = Tabelle nicht zum BEARBEITEN bereit -&gt; Administrator kontaktieren.
        /// </summary>
        internal static string Table_Not_Edit {
            get {
                return ResourceManager.GetString("Table_Not_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Text in Großbuchstaben .
        /// </summary>
        internal static string Text_to_UPPER {
            get {
                return ResourceManager.GetString("Text to UPPER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Datei wird NICHT gespeichert: .
        /// </summary>
        internal static string The_File_is_NOT_saved__ {
            get {
                return ResourceManager.GetString("The File is NOT saved :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Final-Tabelle existiert NICHT! - Muss STOPPEN: .
        /// </summary>
        internal static string The_Final_Table_does_NOT_Exits_______Has_to_STOP__ {
            get {
                return ResourceManager.GetString("The Final Table does NOT Exits !!! - Has to STOP :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der SQL_SERVER wird NICHT ausgeführt .. Korrigieren und erneut versuchen!.
        /// </summary>
        internal static string The_SQL_SERVER_is_NOT_running____Correct_and_try_again__ {
            get {
                return ResourceManager.GetString("The SQL_SERVER is NOT running .. Correct and try again !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Tabletts bereits vorhanden - geben Sie einen neuen Namen ein .
        /// </summary>
        internal static string The_Tray_Name_Exist___Make_a_New_Name {
            get {
                return ResourceManager.GetString("The Tray Name Exist - Make a New Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzername bereits vorhanden - ändern Sie den Namen, um einen neuen Benutzer zu erstellen!.
        /// </summary>
        internal static string The_User_Name_Exist___Change_Name_to_Create_a_New_User__ {
            get {
                return ResourceManager.GetString("The User Name Exist - Change Name to Create a New User !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Monat.
        /// </summary>
        internal static string This_Month {
            get {
                return ResourceManager.GetString("This Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heute.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtanzahl Checkbox_OR_IN: {0:N0}.
        /// </summary>
        internal static string Total_Number_Of_CheckBox_OR_IN___0_N0_ {
            get {
                return ResourceManager.GetString("Total Number Of CheckBox_OR_IN: {0:N0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtanzahl Checkbox_SPD: {0:N0}.
        /// </summary>
        internal static string Total_Number_Of_CheckBox_SPD___0_N0_ {
            get {
                return ResourceManager.GetString("Total Number Of CheckBox_SPD: {0:N0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablettbezeichnung:.
        /// </summary>
        internal static string Tray_Description {
            get {
                return ResourceManager.GetString("Tray_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabletsperre.
        /// </summary>
        internal static string Tray_Lock {
            get {
                return ResourceManager.GetString("Tray_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablettname.
        /// </summary>
        internal static string Tray_Name {
            get {
                return ResourceManager.GetString("Tray_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabletts in der Datenbank:.
        /// </summary>
        internal static string Tray_s_in_Database__ {
            get {
                return ResourceManager.GetString("Tray\'s in Database :", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabletts: {0:N0}.
        /// </summary>
        internal static string Trays___0_N0_ {
            get {
                return ResourceManager.GetString("Trays: {0:N0}", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisierung erneut versuchen....
        /// </summary>
        internal static string Try_Update_again___ {
            get {
                return ResourceManager.GetString("Try Update again...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefiniertes Problem gefunden ... Bitte melden.
        /// </summary>
        internal static string Undefined_Issue {
            get {
                return ResourceManager.GetString("Undefined_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben gespeicherte Daten!.
        /// </summary>
        internal static string Unsaved_Data {
            get {
                return ResourceManager.GetString("Unsaved_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bis Heute.
        /// </summary>
        internal static string Until_ToDay {
            get {
                return ResourceManager.GetString("Until ToDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code aktualisieren.
        /// </summary>
        internal static string Update_Code {
            get {
                return ResourceManager.GetString("Update_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende der Aktualisierung.
        /// </summary>
        internal static string Update_Time_End {
            get {
                return ResourceManager.GetString("Update_Time_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start der Aktualisierung.
        /// </summary>
        internal static string Update_Time_Start {
            get {
                return ResourceManager.GetString("Update_Time_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Überprüfung fehlgeschlagen!.
        /// </summary>
        internal static string Write__Verification_Failed__ {
            get {
                return ResourceManager.GetString("Write  Verification Failed !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In CSV-Datei schreiben FEHLGESCHLAGEN!.
        /// </summary>
        internal static string Write_to_CSV_file_FAILED__ {
            get {
                return ResourceManager.GetString("Write to CSV file FAILED !", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie sind dabei, Dateien zu löschen, die älter sind als: .
        /// </summary>
        internal static string You_are_about_to_Delete_files_that_are_Older_than_ {
            get {
                return ResourceManager.GetString("You are about to Delete files that are Older than:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie haben den Pfad geändert, an dem sich die aktualisierten Dateien befinden.  Vorgang abbrechen?.
        /// </summary>
        internal static string You_have_Changed_the_Path_to_where_Updated_Files_is_Located___Cancel_this_operation__ {
            get {
                return ResourceManager.GetString("You have Changed the Path to where Updated Files is Located.  Cancel this operati" +
                        "on ?", resourceCulture);
            }
        }
    }
}
