// <auto-generated />
namespace Caretag_Class.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PackingPt4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PackingPt4));
        
        string IMigrationMetadata.Id
        {
            get { return "202211231245421_PackingPt4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
