name: Caretag automatic build

on: [push, workflow_dispatch]

jobs:
  build-solution:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1  
        with:
          vs-version: '[17.4)'
      
      - name: Restore NuGet packages
        run:  nuget restore Caretag.sln
        
      - name: Build solution
        run:  MSBuild.exe Caretag.sln /t:Rebuild /p:"Configuration=Debug;Platform=Any CPU"

      - name: Run tests
        run: vstest.console.exe .\Tests\bin\Debug\net6.0-windows\Tests.dll
